CommonServices: {}

PileupReweighting: {}

EventCleaning:
  runEventCleaning: True

Jets:
  - containerName: AnaLargeRJets
    jetCollection: AntiKt10UFOCSSKSoftDropBeta100Zcut10Jets
    #runBoostedJetTagger: False
    BoostedJetTagger:
      ConfigFile: /eos/atlas/atlascerngroupdisk/perf-jets/LocalStorage/TAGGING/PreliminaryConfigs/WTagger/WTagger_AntiKt10UFOSoftDrop_ParT_FixSigEff50.dat
      CalibArea: Local
      IsMC: True ### to remove

  - containerName: AnaJets
    jetCollection: AntiKt4EMPFlowJets
    runJvtUpdate: True

#JetJvtAnalysisConfig:
#  - name: weight_jvt_effSF
#    description: the event-level JVT efficiency SF

#BoostedJetTaggersConfig:
#  - name: test_tagger
#    description: tagger decision

Output:
  treeName: analysis
  vars:
    - AnaLargeRJets_NOSYS.WTransformer_ConstScore -> jet_WTransformer_ConstScore type=float
  containers:
    jet_: AnaLargeRJets
    "": EventInfo
    