ignore 'ERROR Propagation reached the step count limit'
ignore 'ERROR Propagation reached the step count limit'
ignore 'ERROR Propagation failed: PropagatorError:.* Propagation reached the configured maximum number of steps with the initial parameters'
