syntax = "proto3";


message EventInfoMessage {
   uint32  runNumber         = 1;
   uint64  eventNumber       = 2;
   uint32  lumiBlock         = 3;
   uint32  timeStamp         = 4;
   uint32  timeStampNSOffset = 5;
   uint32  bcid              = 6;
   uint32  extendedLevel1ID  = 7;
}

// protobuf maps cannot directly contain repeated fields,
// so we wrap the vectors.
// tests with protobuf fixed32 should be done
// in certain applications (e.g. BS it may allow to avoid copies) 
message UIntVector {
  repeated uint32 values = 1;
}

message IntVector {
  repeated sint32 values = 1;
}

message FloatVector {
  repeated float values = 1;
}

message DoubleVector {
  repeated double values = 1;
}


message OffloadMessage {
  string identifier = 1;
  EventInfoMessage event = 2;
  map<string, UIntVector> uint_branches  = 3;
  map<string, IntVector>  int_branches   = 4;
  map<string, FloatVector> float_branches = 5;
  map<string, DoubleVector> double_branches = 6;
}

service UniversalOffloadService {
  rpc doComputation(OffloadMessage) returns (OffloadMessage) {}
}

/*
plugin=$LCG_RELEASE_BASE/grpc/1.62.3-d3268/x86_64-el9-gcc14-opt/bin/grpc_cpp_plugin
protoc -I=. \
 --cpp_out=. \
 --grpc_out=. \
 --plugin=protoc-gen-grpc=$plugin \
Message.proto
*/