message TestEventInfo {
   required uint32  runNumber         = 1;
   required uint64  eventNumber       = 2;
   required uint32  lumiBlock         = 3;
   required uint32  timeStamp         = 4;
   required uint32  timeStampNSOffset = 5;
   required uint32  bcid              = 6;
   optional uint32  extendedLevel1ID  = 7;
}

message TestInputData {
  required TestEventInfo eventInfo = 1;
  required string ID = 2;
  repeated int32 data = 3;
}

// some notion of validity of the response will be needed
// the ID should be probably smart enough to veryfy if the reponse is to the same request
message TestOutputData {
  required TestEventInfo eventInfo = 1;
  required string ID = 2;
  repeated int32 data = 3;
}



service TestService {
  rpc doComputation(TestInputData) returns (TestOutputData) {}
}

// generate code with:
// plugin=$LCG_RELEASE_BASE/grpc/1.62.3-d3268/x86_64-el9-gcc14-opt/bin/grpc_cpp_plugin
// protoc -I=. \
//  --cpp_out=. \
//  --grpc_out=. \
//  --plugin=protoc-gen-grpc=$plugin \
// TestMessages.proto