# To enable vitis analyzer analysis, set the environment variable
# export XRT_INI_PATH=/path-to/xrt.ini 
# or have a copy of this file in the run directory
# More options of xrt.ini can be found in the 
# Vitis Unified Software Platform Documentation (UG1393)

[Debug]
device_trace = fine
host_trace = true
opencl_trace = true
